# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-16 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oi_seattracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='oi_seattracker.Participant', verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'participant uploaded file',
                'verbose_name_plural': 'participant uploaded files',
            },
        ),
        migrations.CreateModel(
            name='PrintRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_request', to='oi_ghostwriter.Backup', verbose_name='Printed file')),
            ],
            options={
                'verbose_name': 'printed file',
                'verbose_name_plural': 'printed files',
            },
        ),
    ]
