# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-13 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('ip_address', models.GenericIPAddressField(primary_key=True, protocol='IPv4', serialize=False)),
                ('mac_address', macaddress.fields.MACAddressField(blank=True, integer=True, null=True)),
                ('nice_name', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Healthcheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.TextField(choices=[('loadavg', 'Load average'), ('numcpus', 'Processor count'), ('homefree', 'Home mountpoint free space'), ('ntfsfree', 'Host NTFS mountpoint free space'), ('ramfree', 'Free RAM memory')])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.FloatField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oi_seattracker.Computer')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('computer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oi_seattracker.Computer')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='oi_seattracker.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='healthcheck',
            unique_together=set([('computer', 'parameter')]),
        ),
    ]
